AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A simple REST API with a single AWS Lambda function that returns a greeting.

Resources:

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: src/
      MemorySize: 128
      Timeout: 5
      Events:
        GreetingApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET

Outputs:
  ApiUrl:
    Description: "URL of the deployed API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
